const translations = {
  ar: {//yassin
    home: "الرئيسيه",
    about: "تاريخنا",
    serv: "خدماتنا",
    project: "مشاريعنا",
    contact: "اتصل بنا",
    footer: "  © جميع الحقوق محفوظة",
    loca: " 165 عنوان المقر الرئيسي : مدينة 6 أكتوبر المنطقة الصناعية الثالثة قطعة رقم",
    phone: "رقم الهاتف : 01282756122",
    title5: "  العديد من المنتجات",
    title6:"تعرف اكثر ",
    contactus: "تواصل معنا",
    c1:"المتحف المصري الكبير",
    c2:"مركز مجدي يعقوب للقلب",
    c3:"مطار سفينكس",
    c4:"مستشفى 500 500",
    c5:"مطار برج العرب ",
    c6:"الجامعة اليابانية في برج العرب",
    c7:"القطار الكهربائي السريع",
    c8:"محطة تحلية مياه حدائق اكتوبر",
    hd: "الشركة المصرية للخرسانة والهندسة",
    time:"خدمه على مدار الساعة",
    read1:"تُعدّ الشركة رائدة في توريد وتصنيع جميع أنواع الخرسانة. تأسست عام 1982، وهي من أوائل شركات الخرسانة الجاهزة في جمهورية مصر العربية.",
    read2:"لذلك، تتمتع الشركة بخبرة واسعة في مجال الخرسانة عالية الجودة والمتخصصة، بما في ذلك الخرسانة خفيفة الوزن، والخرسانة الثقيلة، والخرسانة الشفافة، والخرسانة الملونة المطبوعة، والخرسانة ذاتية الدمك، وغيرها من الخلطات الخرسانية المتخصصة.",
    read3:"وقد مكّن هذا الشركة من العمل على مشاريع كبرى مثل مركز مجدي يعقوب للقلب، والمتحف المصري الكبير، ومشروع السكك الحديدية عالية السرعة، ومشاريع أخرى متخصصة للغاية.",
    read4:"لذلك فكرت الشركة في الحل العملي في السوق المصري",
    coloredconc:"الخرسانة الملونة هي خرسانة مُعززة بأصباغ طبيعية أو صناعية لإنتاج مجموعة واسعة من الألوان الجذابة. تجمع هذه الخرسانة بين القوة والمتانة والجمال، مما يجعلها مثالية للأرصفة والساحات والحدائق والواجهات والمشاريع المعمارية الزخرفية. تتميز الخرسانة الملونة بطول عمرها، وقلة صيانتها، ومقاومتها للبهتان عند إنتاجها بشكل صحيح.",
    lightconc:"الخرسانة الخفيفة نوع من الخرسانة يُصنع باستخدام ركام خفيف الوزن أو مواد مملوءة بالهواء لتقليل كثافتها. توفر هذه الخرسانة عزلًا حراريًا جيدًا، وتُخفّض الوزن الإجمالي للهياكل، وتُحسّن كفاءة البناء. تُستخدم الخرسانة الخفيفة على نطاق واسع في المباني والجسور والعناصر مسبقة الصب ومشاريع البناء الشاهقة.",
    self:"الخرسانة ذاتية الدمك (SCC) هي خرسانة عالية السيولة تُفرد وتملأ القوالب دون الحاجة إلى اهتزاز. توفر هذه الخرسانة جودة سطح ممتازة، وتحسن كفاءة البناء، وتضمن دمكًا متجانسًا، حتى في الهياكل المسلحة بكثافة. تُستخدم الخرسانة ذاتية الدمك على نطاق واسع في المباني الشاهقة والجسور والعناصر مسبقة الصب والمشاريع الإنشائية المعقدة.",
    fiber:"الخرسانة المسلحة بالألياف هي خرسانة تحتوي على ألياف خاصة، مثل الفولاذ أو الزجاج أو الألياف الاصطناعية، لتحسين قوتها ومتانتها. فهي تساعد على تقليل التشققات، وزيادة مقاومة الصدمات، وتعزيز الأداء على المدى الطويل. وتُستخدم الخرسانة المسلحة بالألياف على نطاق واسع في الأرضيات الصناعية، والأرصفة، والأنفاق، والعناصر مسبقة الصب، ومشاريع البنية التحتية.",
    stmped:"الخرسانة المطبوعة نوعٌ من الخرسانة الزخرفية، مصممة لمحاكاة مظهر الحجر الطبيعي أو الطوب أو البلاط أو الخشب. تجمع هذه الخرسانة بين المتانة واللمسة النهائية الجذابة، مما يجعلها مثالية للأرصفة وممرات السيارات والباحات والحدائق والأماكن العامة. تتميز الخرسانة المطبوعة بسهولة صيانتها، وانخفاض تكلفتها، وتوفرها بتشكيلة واسعة من الأنماط والألوان.",
    perm:"الخرسانة النفاذة نوع خاص من الخرسانة يسمح بمرور الماء عبر سطحها إلى باطن الأرض. وهي تساعد على تقليل جريان المياه السطحية، وتحسين الصرف، وتغذية المياه الجوفية. تُستخدم الخرسانة النفاذة عادةً في مواقف السيارات، والأرصفة، والممرات، وغيرها من مشاريع التنمية الحضرية المستدامة.",
    magdi:"مركز مجدي يعقوب العالمي للقلب هو مركز طبي عالمي المستوى، مُكرّس لتقديم رعاية قلبية متقدمة، وإجراء البحوث الطبية، وتوفير التدريب المهني. يهدف المركز إلى تقديم علاج عالي الجودة للمرضى من جميع الأعمار، بغض النظر عن قدرتهم على الدفع، مع تعزيز الابتكار في طب القلب والأوعية الدموية، وتحسين خدمات الرعاية الصحية في مصر والمنطقة.",
    m500:"مستشفى 500500 هو مشروع طبي غير ربحي في مصر، يُعنى بتقديم رعاية صحية متطورة، لا سيما لمرضى السرطان. ويهدف إلى توفير تشخيص وعلاج وبحوث عالية الجودة باستخدام أحدث التقنيات الطبية. ويعتمد المستشفى على التبرعات، ويسعى إلى تطوير خدمات الرعاية الصحية وتوفير العلاج للمرضى المحتاجين.",
    borg:"تُعد محطة برج العرب للقطار فائق السرعة محطةً رئيسيةً على شبكة السكك الحديدية فائقة السرعة في مصر. صُممت المحطة لتوفير نقل سريع وفعال ومستدام، يربط برج العرب بالمدن الرئيسية في جميع أنحاء مصر. وتدعم المحطة حركة الركاب والتنمية الاقتصادية، وتُحسّن الوصول إلى الوجهات الصناعية والتجارية والسياحية.",
    mbrg:"يُعدّ مطار برج العرب الدولي المطار الدولي الرئيسي الذي يخدم الإسكندرية والمنطقة المحيطة بها. يوفر المطار رحلات داخلية ودولية، ويضمّ مرافق حديثة للمسافرين وخدمات سفر فعّالة. ويلعب المطار دوراً هاماً في دعم السياحة والأعمال والتنمية الاقتصادية في شمال مصر.",
    msf:"مطار سفينكس الدولي مطار حديث يقع بالقرب من أهرامات الجيزة والمتحف المصري الكبير. شُيّد لدعم السياحة وتخفيف الازدحام في مطار القاهرة الدولي. يخدم المطار الرحلات الداخلية والدولية، ويوفر مرافق حديثة وسهولة الوصول إلى أهم المعالم السياحية في مصر.",
    water:"محطة معالجة المياه في حدائق أكتوبر مشروع حديث للبنية التحتية المائية، يساهم في توفير إمدادات موثوقة من المياه النظيفة للمناطق السكنية والحضرية. وتستخدم المحطة تقنيات معالجة متطورة لتحسين جودة المياه، ودعم الإدارة المستدامة للموارد، وتلبية الطلب المتزايد على المياه الآمنة في منطقة حدائق أكتوبر.",
    japan:"جامعة مصر واليابان للعلوم والتكنولوجيا هي جامعة بحثية رائدة تأسست من خلال التعاون بين مصر واليابان. تقدم الجامعة تعليمًا عالي الجودة في الهندسة والعلوم والتكنولوجيا، وفقًا للنموذج التعليمي الياباني. وتركز الجامعة على الابتكار والبحث العلمي والتعلم التطبيقي، وإعداد الخريجين لمواكبة معايير الصناعة العالمية.",
    muz:"يُعدّ المتحف المصري الكبير أحد أكبر المتاحف الأثرية في العالم، ويقع بالقرب من أهرامات الجيزة في مصر. يعرض المتحف آلاف القطع الأثرية المصرية القديمة، بما في ذلك المجموعة الكاملة لكنوز الملك توت عنخ آمون. ويضم قاعات عرض حديثة، وشاشات تفاعلية، وإطلالات خلابة على الأهرامات. ويهدف المتحف المصري الكبير إلى الحفاظ على تاريخ مصر العريق، وتزويد الزوار بتجربة ثقافية فريدة.",
    custm:"خدمة العملاء : 01285558135",
    tech:"الدعم الفني : 01221555598",
    p1:"مجمع مبارك للاستوديوهات بالانتاج الاعلامى",
    p2:"فندق موفنبيك بالانتاج الاعلامى",
    p3:"ماجيك لاند",
    p4:"نادى الاعلاميين بالانتاج الاعلامى",
    p5:"فندق هيليتون اكتوبر بالدريم لاند",
    p6:"فندق شيراتون اكتوبر بالدريم لاند",
    p7:"دريم بارك",
    p8:"دريم لاند",
    p9:"مجمع عمارات الاميرالد بالدريم لاند",
    p10:"هايبر وان",
    p11:"مجمع يونيون اير الصناعى",
    p12:"مجمع يونيفرسال الصناعى",
    p13:"مصنع مرسيدس للسيارات",
    p14:"مصنع دايو موتورز ايجيبت للسيارات",
    p15:"مصنع سوزوكى ايجيبت للسيارات",
    p16:"مصنع نيسان ايجيبت للسيارات",
    p17:"مصنع BMW",
    p18:"مصنع المجموعة البافارية",
    p19:"مصنع بروكتر اند جامبل",
    p20:"مصنع ليفر مصر",
    p21:"مصنع البابطين للاعمدة الانارة",
    p22:"نادى نقابة المهندسين 6 اكتوبر",
    p23:"مجمع عمارات السرايا",
    p24:"دايموند مول",
    p25:"سيتى استارز اكتوبر",
    p26:"مصنع فلورا للصناعات الورقية",
    p27:"مجمع معاهد الحصرى",
    p28:"مسجد الشيخ الحصرى",
    p29:"مصنع الرشيدى للميزان",
    p30:"مصنع نستله",
    p31:"مصنع دولسى",
    p32:"مصنع سيديكو للادوية",
    p33:"مصنع سيجماتك للادوية",
    p34:"مصنع لليلى مصر للادوية",
    p35:"مصنع الكان فرما للادوية",
    p36:"مصنع حكمة للادوية",
    p37:"مصنع كونكوريت للملابس",
    p38:"مصنع العالمية للملابس",
    p39:"مصنع براندز للملابس",
    p40:"القرية الذكية مبنى B4",
    p41:"القرية الذكية مبنى التوثيق الحضارى والمسجد",
    p42:"مصنع سيراميكا الفا",
    p43:"مصنع هينكل ادهيسفزمصر",
    p44:"مصنع البردى للورق - فاين",
    p45:"مجمع مدارس نيو مانور هاوس",
    p46:"مستشفى دار الفؤاد",
    p47:"جامعة مصر للعلوم والتكنولوجيا",
    p48:"جامعة 6 اكتوبر",
    p49:"جامعة نوال الدجوى",
    p50:"مدينة الثقافة والعلوم",
    p51:"فيلات بيفرلى هيلز",
    p52:"فيلات حى النسايم 6 اكتوبر",
    p53:"فيلات حى الريحانة 6 اكتوبر",
    p54:"فيلات جاردنيا 6 اكتوبر",
    p55:"مبنى الورش والمخازن بالشرقية للدخان",
    p56:"مبنى البنزينة بالشرقية للدخان",
    p57:"مصنع روثمان بالشرقية للدخان",
    p58:"مصنع مارلبورو بالشرقية للدخان",
    p59:"فيلات رويال هيلز",
  
  },

  en: {
    home: "home",
    about: "about",
    serv: "services",
    project: "projects",
    contact: "contact",
    footer: "© All rights reserved",
    loca: "Headquarters Address: 6th October City - the third industrial zone plot number 165",
    phone: "phone number: 01282756122",
    title5: "Many products",
    title6:"Learn more",
    contactus:"Contact us",
    c1:"The Grand Egyptian Museum",
    c2:"Magdi Yacoub Heart Center",
    c3:"Sphinx Airport",
    c4:"500 500 Hospital",
    c5:"Burj Al Arab Airport",
    c6:"Japanese University in Burj Al Arab",
    c7:"High-speed electric train",
    c8:"October Gardens Water Desalination Plant",
    hd: "Elmasria for concrete and Engineering Company",
    time:"24-hour service",
    read1:"is a pioneer in the supply and manufacturing of all types of concrete. Established in 1982, it is one of the first ready-mix concrete companies in the Arab Republic of Egypt. ",
    read2:"Therefore, the company has extensive expertise in quality and specialized concretes, including lightweight, heavyweight, transparent, colored stamped concrete, self-compacting concrete, and other specialized concrete mixes. ",
    read3:"This has enabled the company to work on major projects such as the Magdi Yacoub Heart Center, the Grand Egyptian Museum, the High-Speed Rail project, and other highly specialized projects.",
    read4:"So the company considered the concrete solution in the Egyptian market",
    coloredconc:"Colored Concrete is concrete enhanced with natural or synthetic pigments to create a wide range of attractive colors. It combines strength and durability with aesthetic appeal, making it ideal for sidewalks, plazas, parks, facades, and decorative architectural projects. Colored concrete is long-lasting, low-maintenance, and resistant to fading when properly produced.",
    lightconc:"Lightweight Concrete is a type of concrete made with lightweight aggregates or air-filled materials to reduce its density. It offers good thermal insulation, lowers the overall weight of structures, and improves construction efficiency. Lightweight concrete is widely used in buildings, bridges, precast elements, and high-rise construction projects.",
    self:"Self-Compacting Concrete (SCC) is a highly flowable concrete that spreads and fills formwork without the need for vibration. It provides excellent surface quality, improves construction efficiency, and ensures uniform compaction, even in heavily reinforced structures. SCC is widely used in high-rise buildings, bridges, precast elements, and complex structural projects.",
    fiber:"Fiber-Reinforced Concrete (FRC) is concrete that contains special fibers, such as steel, glass, or synthetic fibers, to improve its strength and durability. It helps reduce cracking, increases impact resistance, and enhances long-term performance. Fiber-reinforced concrete is widely used in industrial floors, pavements, tunnels, precast elements, and infrastructure projects.",
    stmped:"Stamped Concrete is a decorative type of concrete designed to replicate the appearance of natural stone, brick, tile, or wood. It combines durability with an attractive finish, making it ideal for sidewalks, driveways, patios, parks, and public spaces. Stamped concrete is low-maintenance, cost-effective, and available in a wide variety of patterns and colors.",
    perm:"Permeable Concrete is a special type of concrete that allows water to pass through its surface into the ground. It helps reduce surface runoff, improve drainage, and recharge groundwater. Permeable concrete is commonly used for parking areas, sidewalks, walkways, and other sustainable urban development projects.",
    magdi:"Magdi Yacoub Global Heart Centre is a world-class medical center dedicated to providing advanced heart care, medical research, and professional training. The center aims to offer high-quality treatment for patients of all ages, regardless of their ability to pay, while advancing innovation in cardiovascular medicine and improving healthcare services in Egypt and the region.",
    m500:"500500 Hospital is a non-profit medical project in Egypt dedicated to providing advanced healthcare, especially for cancer patients. It aims to offer high-quality diagnosis, treatment, and research using modern medical technology. The hospital is supported by donations and seeks to improve healthcare services while making treatment accessible to patients in need.",
    borg:"Borg El Arab High-Speed Rail Station is a key station on Egypt’s high-speed rail network. It is designed to provide fast, efficient, and sustainable transportation, connecting Borg El Arab with major cities across Egypt. The station supports passenger mobility, economic development, and improved access to industrial, commercial, and tourist destinations.",
    mbrg:"Borg El Arab International Airport is the main international airport serving Alexandria and the surrounding region. It provides domestic and international flights, offering modern passenger facilities and efficient travel services. The airport plays an important role in supporting tourism, business, and economic development in northern Egypt.",
    msf:"Sphinx International Airport is a modern international airport located near the Pyramids of Giza and the Grand Egyptian Museum. It was built to support tourism and reduce congestion at Cairo International Airport. The airport serves both domestic and international flights, offering modern facilities and convenient access to major tourist attractions in Egypt.",
    water:"October Gardens Water Treatment Facility is a modern water infrastructure project that helps provide a reliable supply of clean water for residential and urban development. The facility uses advanced treatment technologies to improve water quality, support sustainable resource management, and meet the growing demand for safe water in the October Gardens area.",
    japan:"Egypt-Japan University of Science and Technology is a leading research university established through cooperation between Egypt and Japan. It offers high-quality education in engineering, science, and technology, following the Japanese model of education. The university focuses on innovation, scientific research, practical learning, and preparing graduates to meet global industry standards.",
    muz:"The Grand Egyptian Museum (GEM) is one of the largest archaeological museums in the world. It is located near the Pyramids of Giza, Egypt. The museum displays thousands of ancient Egyptian artifacts, including the complete collection of King Tutankhamun's treasures. It features modern exhibition halls, interactive displays, and stunning views of the pyramids. The GEM aims to preserve Egypt's rich history and provide visitors with a unique cultural experience.",
    custm:"Customer service : 01285558135",
    tech:"Technical support : 01221555598",
    p1:"Al Mubarak, media production studios",
    p2:"Hotel Movenpick media production",
    p3:"Magic Land",
    p4:"Media Club production Information",
    p5:"Hotel Heliton October Baldereym Land",
    p6:"Sheraton Hotel October Baldereym Land",
    p7:"Dream Park",
    p8:"Dreamland",
    p9:"Complex Buildings Alamirald Baldereym Land",
    p10:"Hyper one",
    p11:"Union Air Industrial Complex",
    p12:"Universal Industrial Complex",
    p13:"The manufacturer of Mercedes cars",
    p14:"Sales of Daewoo Motors Egypt for cars",
    p15:"Factory Suzuki Motor Egypt",
    p16:"Nissan's plant Egypt for cars",
    p17:"Sales of BMW cars",
    p18:"Factory Group Bavarian",
    p19:"Procter & Gamble plant",
    p20:"Factory to flee Egypt",
    p21:"Factory Babtain lampposts",
    p22:"Alfa Ceramica",
    p23:"Factory Hinkel Adhesfzmsr",
    p24:"Factory papyrus paper (FINE)",
    p25:"New Park Manor House School",
    p26:"Dar Al Fouad Hospital",
    p27:"Misr University for Science and Technology",
    p28:"6 October University",
    p29:"University of Nawal el Dogy",
    p30:"City of Culture and Science",
    p31:"Club Bar Mouhandisin 6th of October",
    p32:"Al-Saraya Real Estate",
    p33:"Diamond Mall",
    p34:"City Astarz October",
    p35:"Factory Flora of Paper Industries",
    p36:"Complex institutes exclusive",
    p37:"Mosque of Sheikh Al-Hosiery",
    p38:"Factory Rasheedy balance,",
    p39:"Nestle plant",
    p40:"Factory Dulce",
    p41:"Factory SEDICO Pharmaceuticals",
    p42:"Factory Sijmatk Pharmaceuticals",
    p43:"Factory of the following Egypt Pharmaceuticals",
    p44:"Factory Alkan Pharma Pharmaceuticals",
    p45:"The manufacturer of the wisdom of the medicine",
    p46:"Factory Kounkorit Clothing",
    p47:"Factory of the World Clothing",
    p48:"Factory Brands of clothes",
    p49:"Smart Village Building B4",
    p50:"The Smart Village Building Documentation of cultural and the mosque",
    p51:"Royal Hills Villas",
    p52:"Beverly Hills Villas",
    p53:"Villas neighborhood alnsaym October 6",
    p54:"Villas neighborhood Alrihanp October 6",
    p55:"Villas Jardnia October 6",
    p56:"Building workshops and stores the eastern area of smoke",
    p57:"Building Albenzinp eastern area of the smoke",
    p58:"Factory Rothman eastern area of the smoke",
    p59:"The manufacturer of the eastern area of Marlboro smoke",






  }
};
function changeLang(lang) {

  document.documentElement.dir =
    lang === "ar" ? "rtl":"ltr";

  document.documentElement.lang = lang;

  document.querySelectorAll("[data-key]").forEach(el => {
    const key = el.dataset.key;
    el.textContent = translations[lang][key];
  });
//yassin
  localStorage.setItem("language", lang);
}
window.addEventListener("load", () => {
  const savedLang =
    localStorage.getItem("language") || "ar";

  changeLang(savedLang);
});